String teacherName = "Tess Løvgreen";
int daysInAYear = 365;
String city = "København";
boolean isHappy = true;
int sixtyDaysInHours = 60*24;
double decemberTwentysecond = 22.12 // jeg kunne ikke finde på et godt navn til den her
String helloMessage = "Hej, jeg hedder "+teachername;
boolean isAngry = false;
double mathQuestion = 2.2+33;
char letterS = 'S';
